# Debug option (Gunakan jika kalian mengetahui apa ini)
debug: false

###############################################
# Midtrans Section
###############################################
# Bagian ini merupakan bagian paling penting dari plugin ini
# Harus di configure dengan hati hati
###############################################
# Configuration Explanation:
# (midtrans)
#   (production-mode) - Set ke 'true' jika ingin menggunakan mode sandbox
#   (production)
#     (client-key) - Masukan dengan client key dari Midtrans production environment
#     (server-key) - Masukan dengan server key dari Midtrans production environment
#   (sandbox)
#     (client-key) - Masukan dengan client key dari Midtrans sandbox environment
#     (server-key) - Masukan dengan server key dari Midtrans sandbox environment
###############################################
midtrans:
  production-mode: false
  production:
    client-key: "YOUR_PRODUCTION_CLIENT_KEY"
    server-key: "YOUR_PRODUCTION_SERVER_KEY"
  sandbox:
    client-key: "YOUR_SANDBOX_CLIENT_KEY"
    server-key: "YOUR_SANDBOX_SERVER_KEY"

# Masukan port dengan port yang terbuka di server anda.
# Jika anda menggunakan shared-hosting, minta kepada pengelola hosting untuk
# memberikan open port agar bisa digunakan, port ini bertujuan untuk komunikasi antar
# Midtrans dan server anda.
port: 80

# Path ini digunakan sebagai path untuk http request yang akan diterima oleh plugin ini
# Selain mengatur config ini, anda juga harus merubah 'Payment Notification URL' yang terdapat pada
# (Midtrans -> Pengaturan -> Konfigurasi)
notification-path: "/payment/notification"

# MySQL Credentials
# Jika mysql tidak digunakan atau di disable, maka plugin akan
# menggunakan SQLite database
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: db_donations
  user: root
  password: ''
  useSSL: false
  hikari:
    waitTimeout: 600000
    maxLifetime: 1800000
    publicKeyRetrieval: true

# Apakah kita akan menggunakan avatar message?
use-avatar-message: true

# Messages ini akan mendapatkan kepala dari skin player
# dan message ini akan digunakan jika option (use-avatar-message) dinyalakan
avatar-messages:
  header: "&6&m--------------------------------------------"
  line1: ""
  line2: " &6» &l{player} &ejust donated!"
  line3: " &6» &7Type &6/buy &7to see the store"
  line4: ""
  line5: ""
  line6: " &6Product: {product_name} &7(Rp. {product_price})"
  line7: " &7(( Bantu donasi agar server tetap hidup! ))"
  line8: ""
  footer: "&6&m--------------------------------------------"

# Message ini akan digunakan jika option (use-avatar-message) di non-aktifkan
normal-messages:
  - "&6&m--------------------------------------------"
  - " &6» &l{player} &ejust donated!"
  - " &6Product: {product_name} &7(Rp. {product_price})"
  - ""
  - "&7(( Bantu server kami agar tetap hidup! ))"
  - "&6&m--------------------------------------------"
